server:
  port: 8081
spring:
  application:
    name: liviHub
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/dianping
    username: root
    password: 123456
  jackson:
    default-property-inclusion: non_null # JSON处理时忽略非空字段
  rabbitmq:
    host: localhost
    username: root
    password: 123456
    virtual-host: /
    port: 5672
    listener:
      simple:
        concurrency: 10
        max-concurrency: 10
        prefetch: 1
        auto-startup: true
        default-requeue-rejected: true
    template:
      retry:
        enabled: true
        initial-interval: 1000ms
        max-attempts: 3
        max-interval: 10000ms
        multiplier: 1
  data:
    redis:
      host: localhost
      port: 6379
      lettuce:
        pool:
          max-active: 10
          max-idle: 10
          min-idle: 1
          time-between-eviction-runs: 10s
      database: 0
  mail:
    host: smtp.qq.com
    port: 587
    username: 2831362974@qq.com
    password: #防止泄露 使用环境变量配置
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
  elasticsearch:
    uris: http://localhost:9200 # Elasticsearch 服务地址
    username: elastic # 如果有用户名
    password: MQXwsSgaz1-YuFtg7MhM # 如果有密码
mybatis-plus:
  type-aliases-package: com.hmdp.entity # 别名扫描包
logging:
  level:
    com.hmdp: debug